# Use the official lightweight Python image
FROM python:3.9

# Install Nginx and other dependencies
RUN apt-get update && \
    apt-get install -y nginx && \
    apt-get install -y python3-pip && \
    apt-get install -y openssl

# Copy SSL certificate and private key to the image
#COPY kmeling.info.key /etc/nginx/kmeling.info.key
#COPY kmeling.info.pem /etc/nginx/kmeling.info.pem

# Upgrade pip and install Gunicorn
RUN pip install --upgrade pip && \
    pip install gunicorn

# Set up the Flask application
WORKDIR /app
COPY . /app
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Copy the Nginx configuration file
#COPY nginx.conf /etc/nginx/sites-available/default

# Expose port
EXPOSE 8080
#EXPOSE 8081



# Start Nginx and run the app with Gunicorn
CMD service nginx start && gunicorn --bind 0.0.0.0:8080 run:app
